name: Solar System Workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'features/*'

jobs:
    unit-testing:
        name: unit testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: setup NodeJs Version
          uses: actions/checkout@v4
          with:
            node-version: 18
        - name: Install dependencies
          run: npm install

        - name: unit testing 
          run: npm test
    